### ISSUE TITLE
指示器为数字时出现数组下标越界

### ISSUE THREAD

**Issue by DituLin** [wenchaosong/Banner#1]
在 Banner 类中的 onPageSelected(int position) 函数中，与 youth5201314 的比较少了一下两行
...
if (position == 0) position = count;
if (position > count) position = 1;
...
导致出现数组下标越界

**Comment by wenchaosong** [comment]
@DituLin  你是什么情况出现这样的问题呢？

**Comment by DituLin** [comment]
@wenchaosong 直接跑demo 只要是指数器选为数字类型的，就会出现。比如内置样式预览中，选择 NUM_INDICATOR_TITLE

**Comment by wenchaosong** [comment]
@DituLin  已经发布新的版本，合作愉快

**Comment by DituLin** [comment]
@wenchaosong  OK，多问下，有没有考虑加个循环设置

**Comment by wenchaosong** [comment]
@DituLin  循环设置什么

**Comment by DituLin** [comment]
@wenchaosong 现在这个库是无限循环的，如果是做引导页就不适合，加个 Loop  设置可无限循环或不可循环，我的方法是在 Banner 中加 isLoop 进行判断，但一点都不优雅，@wenchaosong 有啥想法没
