### ISSUE TITLE
这个如果仿魅族banner的话，底部加标题的话该怎么办？

### ISSUE THREAD

**Issue by gsy450896356** [wenchaosong/Banner#10]

**Comment by wenchaosong** [comment]
@gsy450896356  有底部标题的样式啊，你看看文档，有标题的样式有3种

**Comment by gsy450896356** [comment]
你说的应该是原banner库的底部标题把？我是想在当前展示的图的底部加标题，不在控件的底部

**Comment by wenchaosong** [comment]
这样，你把你的需求图片发出来看看

**Comment by gsy450896356** [comment]
![image](https://user-images.githubusercontent.com/19199324/45283269-fb4c0400-b50f-11e8-8921-33a0e6682c02.png)

**Comment by wenchaosong** [comment]
这个要自己实现了，布局里面的东西完全是自己实现的，而且就这个需求也很简单的

**Comment by gsy450896356** [comment]
OK,3Q
