### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by OblivioU** [wenchaosong/Banner#11]
java.lang.IllegalStateException

The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 7, found: 2 Pager id: xxx.xxx.xxx:id/bannerViewPager Pager class: class com.ms.banner.view.BannerViewPager Problematic adapter: class com.ms.banner.Banner$BannerPagerAdapter

**Comment by OblivioU** [comment]
刷新的时候是直接banner.update(list);

**Comment by wenchaosong** [comment]
方便给相关代码看看吗，邮件发也可以

**Comment by bakonMa** [comment]
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 5000, found: 1 Pager id: com.lhp.lo:id/bannerViewPager Pager class: class com.ms.banner.view.BannerViewPager Problematic adapter: class com.ms.banner.Banner$BannerPagerAdapter
    at android.support.v4.view.ViewPager.populate(Unknown Source:617)
    at android.support.v4.view.ViewPager.populate(Unknown Source:2)
    at android.support.v4.view.ViewPager.setOffscreenPageLimit(Unknown Source:40)
    at com.ms.banner.Banner.setOffscreenPageLimit(Unknown Source:4)
    at com.ms.banner.Banner.update(Unknown Source:56)


调用的地方，之前有缓存，比如是2条，刷新后新数据是1条
 //banner 刷新
        bannerList.clear();
        bannerList.addAll(homeNewDetailData.banner_list);
        banner.update(bannerList);

**Comment by bakonMa** [comment]
@Override
        public int getCount() {
            if (mDatas.size() == 1) {
                return mDatas.size();
            } else if (mDatas.size() < 1) {
                return 0;
            } else {
                if (isLoop)
                    //return mDatas.size() + 2;
                    return NUM;
                else
                    return mDatas.size();
            }
        }


5000是你这里的固定值吗？
