### ISSUE TITLE
请问怎样把指示器设置在banner的下方

### ISSUE THREAD

**Issue by zhangbaogithub** [wenchaosong/Banner#13]
就像文档中 自定义指示器模式 那个截图里显示的那样

**Comment by zhangbaogithub** [comment]
我自己琢磨出了一种解决办法，把banner_item布局中的图片设置paddingBottom，让整个banner底部显示出来一部分空白，这样从效果上看就是indicator在banner的下方了

**Comment by wenchaosong** [comment]
@zhangbaogithub  你这个解决办法是不对的，下面的间距被缩短了，我自己试了一下，实现也比较简单，明天上传新代码，今天有点事

**Comment by wenchaosong** [comment]
@zhangbaogithub 已经上传了

**Comment by zhangbaogithub** [comment]
> @zhangbaogithub 已经上传
好的，感谢
