### ISSUE TITLE
怎么设置指示器大小

### ISSUE THREAD

**Issue by siny-yao** [wenchaosong/Banner#14]
用资源图片作为指示器时，怎么设置指示器大小。
同时怎么设置指示器和banner的间距，让其距离banner图片较远。
banner.setIndicatorRes(R.drawable.banner_indicator, R.drawable.banner_indicator_selected);

**Comment by wenchaosong** [comment]
@siny-yao  用资源图片的时候为了防止变形是没有暴露方法去修改指示器大小的，只有让 UI 切个合适的图片，设置指示器和 banner 的间距用 indicator_margin 属性

**Comment by siny-yao** [comment]
indicator_margin 属性会让指示器网上，我想让指示器在banner下边，并且有一段距离

**Comment by wenchaosong** [comment]
@siny-yao 看 #13 ，demo 中有的

**Comment by siny-yao** [comment]
刚好看到，已经实现了，谢谢大大

**Comment by siny-yao** [comment]
> @siny-yao 看 #13 ，demo 中有的
刚好看到，已经实现了，谢谢大大

**Comment by ShuaiJing** [comment]
设置指示器一个长条形，一个圆形，被裁减了，应该是被写死宽高
