### ISSUE TITLE
卡片模式，不设置动画，如何设置卡片的两边的边距

### ISSUE THREAD

**Issue by fenggit** [wenchaosong/Banner#16]
卡片模式，不设置动画，如何设置卡片的两边的边距

**Comment by wenchaosong** [comment]
@fenggit  这个卡片模式是通过 ViewPager 的 PageTransformer 实现的，setScaleX 就是设置两边的边距

**Comment by fenggit** [comment]
> @fenggit 这个卡片模式是通过 ViewPager 的 PageTransformer 实现的，setScaleX 就是设置两边的边距

感谢回复，好的，我去试试，只能手动修改PageTransformer 吗？希望增加配置属性

**Comment by wenchaosong** [comment]
@fenggit  你把我的 ScaleTransformer 复制一份，修改 SCALE_X 的值，值越大边距越大，然后调用 setBannerAnimation(MyScaleTransformer.class)，这个就是一个可以配置的类

**Comment by fenggit** [comment]
> @fenggit 你把我的 ScaleTransformer 复制一份，修改 SCALE_X 的值，值越大边距越大，然后调用 setBannerAnimation(MyScaleTransformer.class)，这个就是一个可以配置的类

那能否获取，卡片模式，两张图片的边距？我想设置图片比例，来动态设置banner高度

**Comment by fenggit** [comment]
> @fenggit 你把我的 ScaleTransformer 复制一份，修改 SCALE_X 的值，值越大边距越大，然后调用 setBannerAnimation(MyScaleTransformer.class)，这个就是一个可以配置的类

那能否获取，卡片模式，两张图片的边距？我想设置图片比例，来动态设置banner高度
