### ISSUE TITLE
BannerViewPager的onAttachedToWindow()方法出现多次异常

### ISSUE THREAD

**Issue by erichyx** [wenchaosong/Banner#17]
![image](https://user-images.githubusercontent.com/10595445/48132435-7b070c80-e2ce-11e8-81a5-927206fa0584.png)

**Comment by wenchaosong** [comment]
@erichyx  onAttachedToWindow 方法在 2.2.3 版本之后就已经注释掉了，你用的是哪个版本的

**Comment by erichyx** [comment]
> @erichyx onAttachedToWindow 方法在 2.2.3 版本之后就已经注释掉了，你用的是哪个版本的

2.2.0

**Comment by wenchaosong** [comment]
@erichyx  用最新版的吧
