### ISSUE TITLE
ViewPager 设置pagemargin 时，上下左右分开

### ISSUE THREAD

**Issue by QianHong** [wenchaosong/Banner#24]
现在设置的话是四周同时，加了margin 我的需求是只有右边margin

**Comment by QianHong** [comment]
![1](https://user-images.githubusercontent.com/22974738/50951744-3c1d4f00-14e9-11e9-8e3a-8bb59e76f9bc.jpg)

需要的是这样的效果。

**Comment by wenchaosong** [comment]
@QianHong  我试了一下,其实蛮简单的,代码我弄好了,但是电脑出了点问题,暂时上传不了,思路就是把那个 mPageMargin 分左,右2个属性,晚点我看看能不能提交代码,你到时用新版就好了

**Comment by QianHong** [comment]
感谢。大佬辛苦了！
