### ISSUE TITLE
怎么去监听滑动，我想要跟天猫首页banner一样滑动banner改变头部块的颜色

### ISSUE THREAD

**Issue by luhuanxml** [wenchaosong/Banner#27]
怎么去监听滑动，我想要跟天猫首页banner一样滑动banner改变头部块的颜色

**Comment by wenchaosong** [comment]
@luhuanxml  setOnPageChangeListener 
类似 viewpager 的滑动监听

**Comment by luhuanxml** [comment]
> @luhuanxml setOnPageChangeListener
> 类似 viewpager 的滑动监听

使用onPageScrolled方法回调处理了该事件，但是在尾部到第一个，和第一个回退到最后一个时，不知道怎么衔接，还有进去后，position是从1开始的。我的banner长度是6个，但是会出现0-7八个数，还是有些问题我的代码如下

![image](https://user-images.githubusercontent.com/19920279/52551189-5b740880-2e16-11e9-9394-06e65359d43b.png)

**Comment by luhuanxml** [comment]
前进是1-7，后退是6-0

**Comment by luhuanxml** [comment]
谢谢，使用你的方案终于实现了
