### ISSUE TITLE
banner 显示时，可否设置默认选中第几张图片

### ISSUE THREAD

**Issue by QianHong** [wenchaosong/Banner#36]
例如，我的banner中有五张图片，在加载完成时让它默认选中第n张

**Comment by wenchaosong** [comment]
@QianHong  一开始就显示第几张,那下面的 indicator 也是显示第几个吗?左右滑动是正常滑动吗?感觉这个需求其实不太好的,应该是后台自己配置轮播图的顺序,第一个就是要展示的

**Comment by wenchaosong** [comment]
@QianHong  假如这次是显示第二张,那下次显示第四张,那你还要改代码,这是不对的,这个需求实现起来很简单,但是不推荐
