### ISSUE TITLE
依赖报错

### ISSUE THREAD

**Issue by JovanLep** [wenchaosong/Banner#37]
ERROR: Failed to resolve: com.github.wenchaosong:Banner:2.3.7
Show in Project Structure dialog
Affected Modules: app

**Comment by JovanLep** [comment]
新建的项目工程 没有其他干扰   依赖都添加了   是因为gradle 版本太高了吗

**Comment by JovanLep** [comment]
麻烦升级兼容一下最高版本的gradle

**Comment by 13731160065** [comment]
你看看build.gradle(Project:xxx)文件里的

**Comment by 13731160065** [comment]
> 麻烦升级兼容一下最高版本的gradle

你看看build.gradle(Project:xxx)里的jcenter()和maven { url 'https://jitpack.io' }有没有加在allprojects下，我的之前加在了repositories下就报你这个错了，加在allprojects下就好了，只是有可能昂，我的gradle是4.6的

**Comment by wenchaosong** [comment]
我刚刚试了一下,是 jitpack 的问题,跟 gradle 没有关系,你可以试试其他 github 开头的库,应该也是一样的问题

**Comment by 13731160065** [comment]
> 我刚刚试了一下,是 jitpack 的问题,跟 gradle 没有关系,你可以试试其他 github 开头的库,应该也是一样的问题

我有个别的问题问问你哈～我们项目里已经有youth.banner了，然后又引入了你的库，之前好好的，引入你这个后运行就报android.view.InflateException: Binary XML file line #6: Error inflating class com.youth.banner.Banner这个错误，注释掉你的库同步一下就好了，如果我即想保留youth.banner又想用你的怎么办，因为项目里已经用了youth.banner，不太好全改

**Comment by wenchaosong** [comment]
@13731160065  那没办法,之前有人说过这个问题,是不能共存的

**Comment by 13731160065** [comment]
> @13731160065 那没办法,之前有人说过这个问题,是不能共存的

哦哦谢谢
