### ISSUE TITLE
支持切换 fragment 吗

### ISSUE THREAD

**Issue by Kenmmm** [wenchaosong/Banner#38]
上面三个 banner，下面3个 fragment 页面切换，如何使用，谢谢

**Comment by wenchaosong** [comment]
各自 fragment 中处理啊,这个就算不是 banner ,其他的东西也是一样要处理的吧, banner 的话无非就是切换 fragment 后,上个 fragment 中 banner 停止轮播,现在的 fragment 开始轮播

**Comment by wenchaosong** [comment]
你遇到的问题是什么?
