### ISSUE TITLE
依赖报错啊兄弟  兼容一下高版本的api啊 不要在25里面游泳了

### ISSUE THREAD

**Issue by JovanLep** [wenchaosong/Banner#39]
依赖报错依赖报错依赖报错，这次删了我就不来了

**Comment by wenchaosong** [comment]
@JovanLep  maven { url 'https://jitpack.io' }  这个你加了没有

**Comment by JovanLep** [comment]
你可以试一下哈  api 在28  maven我加了真滴 ，最新的studio gradle 3.3.2

**Comment by JovanLep** [comment]
新建的工程亲测了 两个新工程  都依赖不成功

**Comment by JovanLep** [comment]
本地lib 试过了没问题  升级了可以没毛病

**Comment by liericiyan** [comment]
> 本地lib 试过了没问题 升级了可以没毛病

老铁，你可能需要vpn
