### ISSUE TITLE
可以自定义指示器的样式不？

### ISSUE THREAD

**Issue by chenyusheng** [wenchaosong/Banner#4]
可以自定义指示器的样式不？
例如我给定两个图片，一张普通的，一张是选中的

**Comment by wenchaosong** [comment]
可以的
app:indicator_drawable_selected="@mipmap/ic_launcher"
app:indicator_drawable_unselected="@mipmap/ic_launcher"

**Comment by chenyusheng** [comment]
我现在选中是需要一个椭圆的，设置了app:indicator_drawable_selected之后，变成了个小正方形了

**Comment by wenchaosong** [comment]
@chenyusheng  并不会改变你本身图片形状的，你可以把 indicator 调大点再看看
app:indicator_height="30dp"
app:indicator_width="30dp"

**Comment by wenchaosong** [comment]
@chenyusheng  好吧，我知道了，指示器创建的时候，是按照给定的宽高，如果图片高度不够，会拉伸

**Comment by chenyusheng** [comment]
所以现在有没有办法解决？或者其他的创建方式。。。帮帮忙~

**Comment by wenchaosong** [comment]
@chenyusheng  有办法，不过要等下，要重新发个版本

**Comment by chenyusheng** [comment]
ok，发个版本之后告诉我下

**Comment by chenyusheng** [comment]
ok,我先试试

**Comment by chenyusheng** [comment]
可以了
![image](https://user-images.githubusercontent.com/11496107/43639926-7b4852fe-9750-11e8-9c50-537c49767d2e.png)
谢谢哈
