### ISSUE TITLE
按下时能否停止自动播放

### ISSUE THREAD

**Issue by liericiyan** [wenchaosong/Banner#40]

**Comment by wenchaosong** [comment]
@liericiyan  按下只能停止当前的轮播,放开又会自动轮播,要停止自动轮播要调用 stopAutoPlay

**Comment by liericiyan** [comment]
> @liericiyan 按下只能停止当前的轮播,放开又会自动轮播,要停止自动轮播要调用 stopAutoPlay

手指按下时轮播没有停止，还在自动播放

**Comment by JovanLep** [comment]
这个我刚改了一下本地库，Banner 里面的viewpager加上了ontouch ，测试过了，暂时没发现别的问题。
       //ViewPager被按下的时候，取消自动滚动
        viewPager.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if (event.getAction() == MotionEvent.ACTION_DOWN) {
                   stopAutoPlay();
                } else if (event.getAction() == MotionEvent.ACTION_UP) {
                  startAutoPlay();
                }
                return false;
            }
        });

**Comment by liericiyan** [comment]
```
 float downX = ev.getX();
                if (mPageLeftMargin != 0 || mPageRightMargin != 0) {
                    if (downX > mPageLeftMargin && downX < mPageRightMargin) {
                        stopAutoPlay();
                    }
                }
```
这段是不是写的有问题啊

**Comment by liericiyan** [comment]
> 这个我刚改了一下本地库，Banner 里面的viewpager加上了ontouch ，测试过了，暂时没发现别的问题。
> //ViewPager被按下的时候，取消自动滚动
> viewPager.setOnTouchListener(new View.OnTouchListener() {
> @override
> public boolean onTouch(View v, MotionEvent event) {
> if (event.getAction() == MotionEvent.ACTION_DOWN) {
> stopAutoPlay();
> } else if (event.getAction() == MotionEvent.ACTION_UP||event.getAction() == MotionEvent.ACTION_CANCEL||event.getAction() == MotionEvent.ACTION_OUTSIDE||) {
> startAutoPlay();
> }
> return false;
> }
> });

多谢，改了一下

**Comment by liericiyan** [comment]
重新了Banner类 :
`public class MyBanner extends Banner {
    public MyBanner(Context context) {
        super(context);
    }

    public MyBanner(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public MyBanner(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        switch (ev.getAction()) {
            case MotionEvent.ACTION_UP:
            case MotionEvent.ACTION_CANCEL:
            case MotionEvent.ACTION_OUTSIDE:
                startAutoPlay();
                break;
            case MotionEvent.ACTION_DOWN:
                stopAutoPlay();
                break;
        }
        return super.dispatchTouchEvent(ev);
    }
}`

**Comment by wenchaosong** [comment]
我看了一下,这个是没有处理好,待会会发一个新版本,用新版本就好了
