### ISSUE TITLE
建议哈 ，没有其他意思，能不能动态设置卡片模式左右展示部分的高度

### ISSUE THREAD

**Issue by JovanLep** [wenchaosong/Banner#41]
自己改库改的很难受
 this.setOnHierarchyChangeListener(new OnHierarchyChangeListener() {
            @Override
            public void onChildViewAdded(View parent, View child) {
                child.setScaleY(minScale);
                child.setAlpha(minAlpha);
            }

            @Override
            public void onChildViewRemoved(View parent, View child) {
            }
        });

**Comment by wenchaosong** [comment]
你这需求不常见,暂时不准备通用,目前只支持初始化的时候设置,不能动态改变,如果你需要,就要你自己改源码了
