### ISSUE TITLE
图片消失

### ISSUE THREAD

**Issue by chshp1234** [wenchaosong/Banner#42]
我现在tab+viewpager+fragment，第一个tab下顶部有banner（本框架），然后我一直切换tab项，再切换回第一个tab，banner里的轮播图会消失

**Comment by wenchaosong** [comment]
我自己的项目从来没出现过哦,我不知道你的实现方式,能提供个简单的 demo 吗

**Comment by chshp1234** [comment]
可以的，描述就是我提的那样，然后我换了好几个banner框架好像都有这样的情况，就是切换tab后再切换回来，banner里的图片就没了。我现在是在fragment的setUserVisibleHint方法里可见时重新banner.update（）临时解决的。

**Comment by wenchaosong** [comment]
@chshp1234  其实我的猜测是你的逻辑有点问题,而且你说的这个 tab+viewpager+fragment 是要用到懒加载的,懒加载处理好是一定不会出现这个情况的

**Comment by chshp1234** [comment]
![banner0](https://user-images.githubusercontent.com/31475629/55707175-90b36600-5a15-11e9-994c-2de3054aa10a.png)
这是刚加载时的正常页面，首页是RV嵌套多TYPE（刚开始使用scrollview嵌套的，情况一样）。
![banner1](https://user-images.githubusercontent.com/31475629/55707258-be98aa80-5a15-11e9-9dad-55109291f776.png)
这是我切换tatab（切换后面几个tab）后再切换回首页时的banner情况

**Comment by chshp1234** [comment]
（不好意思图有点大）
现在我是这样解决的，您看看。
![banner2](https://user-images.githubusercontent.com/31475629/55707315-e556e100-5a15-11e9-9a91-1ce0839b7ae9.png)
![banner3](https://user-images.githubusercontent.com/31475629/55707320-e8ea6800-5a15-11e9-83c6-9516ae6c37cb.png)
起码来回切换是没问题了，但是不知道是banner的问题还是我在使用上有什么没做好的地方

**Comment by wenchaosong** [comment]
@chshp1234  有解决方案是最好的,然后你的这个问题我准备最近直接上个 demo ,到时候你可以参照那个对比你的代码

**Comment by chshp1234** [comment]
> @chshp1234 有解决方案是最好的,然后你的这个问题我准备最近直接上个 demo ,到时候你可以参照那个对比你的代码

好多谢了

**Comment by wenchaosong** [comment]
@chshp1234  最近比较忙,现在才更新 demo,欢迎使用新版本

**Comment by Waterelone** [comment]
我用了最新版本的banner，然后LazyFragment用的也是你的，但是还是会出现banner划着划着会出现空白的情况，操作流程：导航栏我有四个按钮，banner在第一个fragment，然后我点击第四个fragment，在里面跳转了一个界面，然后返回，再点到第一个fragment，滑动banner，会出现空白
