### ISSUE TITLE
修改绘制顺序问题

### ISSUE THREAD

**Issue by DongDian455** [wenchaosong/Banner#45]
你好，多屏显示的时候，我想修改viewpager的绘制顺序已到达中间的卡片是显示在两侧卡片之上，但是BannerViewPager中的getCurrentItem()返回2000多

**Comment by wenchaosong** [comment]
@DongDian455  getCurrentItem 这个方法是不对外开放的,看这个返回是没有意义的.
显示在两侧卡片之上,我推荐你使用 https://github.com/Devlight/InfiniteCycleViewPager

**Comment by DongDian455** [comment]
好的，我去看看，感谢回复
