### ISSUE TITLE
同学你好，有个问题想问一下

### ISSUE THREAD

**Issue by wotoutengleha** [wenchaosong/Banner#46]
这个banner使用挺好的 有一个问题，就是我设置banner图片为圆角图片了，根布局使用cardView实现的，banner切换滑动的时候，圆角careView就变了直角，请问大概是什么原因呢

**Comment by wenchaosong** [comment]
@wotoutengleha  要看你布局怎么设置, imageview 的 scaleType 是不是 fitXY,这些都没问题的话,有可能就是 banner 本身的问题

**Comment by wotoutengleha** [comment]
是设置的 fitXY

**Comment by wenchaosong** [comment]
cardview 里面就只有一个 imageview 吗

**Comment by wotoutengleha** [comment]
是的

**Comment by wotoutengleha** [comment]
其实根布局就一个cardView 设置圆角的情况下，布局什么也不加的情况下，自动滚动切换的时候就变成直角了

**Comment by wenchaosong** [comment]
@wotoutengleha  新上传了 RoundImageView ,推荐使用这个. cardview 会因为 v7 v4 包不一样,圆角显示可能有问题
