### ISSUE TITLE
自定义指示器模式对应的代码是哪个

### ISSUE THREAD

**Issue by wangfengye** [wenchaosong/Banner#47]

**Comment by wenchaosong** [comment]
@wangfengye  参照这个类 CustomViewPagerActivity.java  代码都给你写好了

**Comment by wangfengye** [comment]
看到了,做了个类似爱奇艺app的轮播, 指示器选中状态和未选中状态长度不同,我是通过,自定义drawable的留白控制视觉上的指示器的间隔相等. 你有没有考虑过增加一个选中指示器的宽度控制接口,还有指示器变化动画的接口

**Comment by wenchaosong** [comment]
@wangfengye  指示器的代码完全可以自己实现,动画也可以自己实现

**Comment by wangfengye** [comment]
是的我重改代码实现了功能,我的意思是你的库中指示器的add 和更新 都是私有方法不支持扩展,要改只能改源码

**Comment by wenchaosong** [comment]
@wangfengye  不用改源码  CustomViewPagerActivity 这个类里面自定义指示器完全就是重写了一套
