### ISSUE TITLE
文档最好加上混淆规则

### ISSUE THREAD

**Issue by chenyusheng** [wenchaosong/Banner#5]
# glide 的混淆代码
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
# banner 的混淆代码
-keep class com.ms.banner.** {
    *;
 }

**Comment by wenchaosong** [comment]
glide 的自己视情况加， banner 的已经更新在 readme
