### ISSUE TITLE
无法开放方法来获取当前的Postion或者CurrenPosition

### ISSUE THREAD

**Issue by Wietas** [wenchaosong/Banner#50]

**Comment by Wietas** [comment]
无此getCurrenPosition()方法  可否开放

**Comment by wenchaosong** [comment]
@Wietas  banner.setOnPageChangeListener();  监听这个可以实时获取

**Comment by Wietas** [comment]
@wenchaosong 主要是在外部用到使用viewpager的getCurrentItem;setOnPageChangeListener是确实种方式  需要指定个外部全局变量记录  ；Banner里面有currentItem  看有木有办法开放方法出来   相对方便  或者viewpager开放出来也行

**Comment by wenchaosong** [comment]
@Wietas   这个问题是这样的, currentItem 这个值是实时变化的,就需要不断监听它的变化,否则取出的有可能是错误的,毫无意义啊

**Comment by Wietas** [comment]
好吧  ，，，有时间我看源码改吧，  到时候效果方案or代码提给你哈

**Comment by wenchaosong** [comment]
@Wietas  好的
