### ISSUE TITLE
圆角轮播设置问题

### ISSUE THREAD

**Issue by rhf05290** [wenchaosong/Banner#51]
一个Activity中多个fragment，其中一个fragment的轮播图设置了圆角，其他的也自动变为圆角，不能设置为无圆角效果。老铁们，这个是什么问题？

**Comment by wenchaosong** [comment]
@rhf05290  .setPages(arrList, new CustomViewHolder())   你看看这个方法的第二个参数是不是一样的,一样的就是你说的这个现象,设置成不一样的就行了

**Comment by rhf05290** [comment]
在另外一个fragment中第二个参数传new CustomViewHolder2()也是同样的问题

**Comment by wenchaosong** [comment]
@rhf05290  你可以看下我 demo ,没有这个问题    ViewPager + Fragment + Banner
