### ISSUE TITLE
图片带圆角轮播能设置左右边距吗

### ISSUE THREAD

**Issue by jyl320317** [wenchaosong/Banner#53]

**Comment by wenchaosong** [comment]
@jyl320317  能,你要设置距离哪里的边距

**Comment by jyl320317** [comment]
![image](https://user-images.githubusercontent.com/12275371/57824568-10c7ab00-77ce-11e9-80db-6354aa001d9f.png)
就是距离左右屏幕的边距

**Comment by wenchaosong** [comment]
这种你只要 修改 ScaleTransformer 调整 SCALE_X,去掉 SCALE_Y,然后直接使用 .setBannerAnimation(NewScaleTransformer .class)

**Comment by jyl320317** [comment]
使用ScaleRightFormer调整SCALE_X可以实现，感谢分享👍

**Comment by wenchaosong** [comment]
用 ScaleRightFormer 也可以，其实重点是调整  SCALE_X
