### ISSUE TITLE
关于新需求问题

### ISSUE THREAD

**Issue by yx971072369** [wenchaosong/Banner#54]
假设 轮播图内有5个图片、且每个图片要显示的时间不一样、例如分别5s,10s,15s,3s,8s。且重复轮播、这个问题该如何解决？此类需求多用于多媒体广告机一类

**Comment by TzuChiangLi** [comment]
因吹斯听

**Comment by yx971072369** [comment]
waht?说的什么意思？

**Comment by yx971072369** [comment]
> 因吹斯听

什么意思？

**Comment by TzuChiangLi** [comment]
> > 因吹斯听
> 
> 什么意思？

哈哈哈我的意思是你提的这个需求interesting有趣啊

**Comment by yx971072369** [comment]
> > > 因吹斯听
> > 
> > 
> > 什么意思？
> 
> 哈哈哈我的意思是你提的这个需求interesting有趣啊

哎、碰到了、正在自己改源码

**Comment by wenchaosong** [comment]
@yx971072369  这个是特别的需求,需要你自己特别处理,处理也简单,监听 setOnPageChangeListener 就可以了

**Comment by yx971072369** [comment]
> @yx971072369 这个是特别的需求,需要你自己特别处理,处理也简单,监听 setOnPageChangeListener 就可以了

改好了、照那个原理作者的改的、有需要的话可以加个联系方式、有什么新的问题、可以一起商量解决，QQ:971072369，yyyyy
