### ISSUE TITLE
每个卡片之间的间隔可以修改么 ，现在的间隔有点大

### ISSUE THREAD

**Issue by xyZangGit** [wenchaosong/Banner#55]

**Comment by wenchaosong** [comment]
@xyZangGit 可以的

**Comment by xyZangGit** [comment]
在哪里修改？没找到属性，只看到了app:page_left_margin="15dp"
                                                          app:page_right_margin="15dp"
两个属性

**Comment by wenchaosong** [comment]
@xyZangGit  你用的这个类的话  ScaleTransformer  就是修改 SCALE_X 的值

**Comment by xyZangGit** [comment]
> @xyZangGit 你用的这个类的话 ScaleTransformer 就是修改 SCALE_X 的值

能在具体点么， 我没有用到 ScaleTransformer

**Comment by wenchaosong** [comment]
那我不知道你需求是什么样的啊     你截图看看

**Comment by xyZangGit** [comment]
> 那我不知道你需求是什么样的啊 你截图看看

![image](https://user-images.githubusercontent.com/19574114/58399221-0e950480-808a-11e9-877f-4bc374415480.png)
，这样的banner图，而且我整体把banner放在recycleview第一个item上面，每次我滑动recycleview的时候滑动到 一个的时候总是会卡顿一下，已经设置在他不显示的时候暂停轮播了

**Comment by wenchaosong** [comment]
@xyZangGit  你用 ScaleRightTransformer   调整 SCALE_X 的值就行了   值越小间距越小
