### ISSUE TITLE
bugly报错

### ISSUE THREAD

**Issue by chshp1234** [wenchaosong/Banner#58]
#14904 java.lang.ArithmeticException
divide by zero
com.ms.banner.Banner.onPageSelected(Banner.java:650)

com.ms.banner.Banner.onPageSelected(Banner.java:651)
--
2 androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
3 androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:686)
4 androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:670)
5 androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:2263)
6 com.ms.banner.view.BannerViewPager.onTouchEvent(BannerViewPager.java:23)
7 android.view.View.dispatchTouchEvent(View.java:12527)
8 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)

.....
后面就不截了太多了。

这是2.3.11的版本，刚刚更新2.3.14还没运行

还有那个优化方面的，可以参考参考新的viewpager2控件，这个也是基于RV实现的

**Comment by wenchaosong** [comment]
@chshp1234   好的   待会上个新版本

**Comment by chshp1234** [comment]
> @chshp1234 好的 待会上个新版本

en，谢谢
