### ISSUE TITLE
求教最后一个demo图片的效果指示器怎么弄呢？文档和demo和代码里都没找到

### ISSUE THREAD

**Issue by jiankian** [wenchaosong/Banner#6]

**Comment by wenchaosong** [comment]
@jiankian   要设置指示器样式为 BannerConfig.CUSTOM_INDICATOR，然后设置指示器相应的图片资源就可以了，待会我也更新下 Demo

**Comment by jiankian** [comment]
BannerConfig.CUSTOM_INDICATOR参数当时写了这个没变化，奇怪了
