### ISSUE TITLE
2.3.9版本

### ISSUE THREAD

**Issue by CodingAndroid** [wenchaosong/Banner#60]
java.lang.IndexOutOfBoundsException
Index: 0, Size: 0

1java.util.ArrayList.get(ArrayList.java:437)
2 android.support.v4.view.ViewPager.performDrag(ViewPager.java:2318)
3 android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2236)
4 com.ms.banner.view.BannerViewPager.onTouchEvent(BannerViewPager.java:22)
............

**Comment by wenchaosong** [comment]
@CodingAndroid  用最新的吧
