### ISSUE TITLE
文字和指示器位置不能同时设置？

### ISSUE THREAD

**Issue by RUDNI** [wenchaosong/Banner#69]
现在文字和指示器只能在同一排显示，是否可以支持文字和指示器各一个设置位置的属性

**Comment by wenchaosong** [comment]
@RUDNI  最近比较忙, 可以添加    你暂时可以先改源码    或者提交 pr

**Comment by wenchaosong** [comment]
@RUDNI  想了一下, 这个还是交给你们需要自定义的去实现吧, 可以自己重写布局, 自定义文字和指示器, 具体参考 demo 自定义布局
