### ISSUE TITLE
【建议】适配器方法里的createView 和 onBind整合成一个方法

### ISSUE THREAD

**Issue by sionsxie** [wenchaosong/Banner#72]
@Override
        public Object instantiateItem(ViewGroup container, final int position) {
            if (creator == null) {
                throw new RuntimeException("[Banner] --> The layout is not specified,please set holder");
            }
            View view = creator.createView(container.getContext());
            container.addView(view);

            if (mDatas != null && mDatas.size() > 0) {
                creator.onBind(container.getContext(), toRealPosition(position), 
                mDatas.get(toRealPosition(position)));
            }
            if (listener != null) {
                view.setOnClickListener(new OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        listener.onBannerClick(mDatas, toRealPosition(position));
                    }
                });
            }
            return view;
        }

建议适配器方法里的createView 和 onBind整合成一个方法，比如eq： View createView(Context context, List\<T> list, int position, T data);

这种分开的设置图片源，在和SubsamplingScaleImageView加载大图时，首次前三个会显示不出来

**Comment by wenchaosong** [comment]
@sionsxie  好的建议,不过最近比较忙,你可以直接提 pr

**Comment by wenchaosong** [comment]
@sionsxie  已经发布新版本
