### ISSUE TITLE
update(bannerList) ，bug，数据对象的问题，不能用同一个list对象

### ISSUE THREAD

**Issue by bakonMa** [wenchaosong/Banner#79]
banner.update(bannerList);
初始化时setPages(bannerList, new BannerView())
bannerList：同一个对象，你内部处理时【 this.mDatas.clear();】直接把对象清空了，其实你应该内部维护自己的，不要用外部的对象
 public Banner setPages(List<?> datas, BannerViewHolder creator) {
        **this.mDatas = datas;**
        this.creator = creator;
        this.count = datas.size();
        return this;
    }

使用addaAll就不会影响外部的同一个对象了

**Comment by wenchaosong** [comment]
@bakonMa    没看明白, setPages 是第一次调用, 用的是传递过来的集合, update 是后续调用, 做更新集合的操作, 我不知道你想表达什么意思

**Comment by bakonMa** [comment]
谢谢回复
我的情况是：初始化setPages(bannerList)，更新时 修改bannerList内容，然后使用 update(bannerList)更新后banner是空的 
我debug的结果是：update(bannerList)中 this.mDatas.clear();把我update的数据 又清空了，因为是同一个对象的问题，我只能换一个update(listB)，才可以
1:你测试一下update，是否重新
2:修改建议：初始化中setPages() 中this.mDatas = datas修改为this.mDatas.addAll(datas)

可以加我qq：762713299沟通一下 谢谢

**Comment by wenchaosong** [comment]
@bakonMa  已经优化发布新版本了
