### ISSUE TITLE
关于卡片模式下只有一个Item时的优化

### ISSUE THREAD

**Issue by FeverCombo3** [wenchaosong/Banner#8]
如果list只有一项，显示的时候左右都会多出一点，给人还有多余项目的错觉，所以在BannerPagerAdapter的getCount方法中最好做出如下判断：
 @Override
        public int getCount() {
            if(mDatas.size() == 1){
                return mDatas.size();
            }else {
                return mDatas.size() + 2;
            }

        }
这样就没有问题了。

**Comment by wenchaosong** [comment]
@FeverCombo3  嗯，已经优化了
