### ISSUE TITLE
最新版本卡片模式下，向左或者向右滑动图片的边会贴在一块

### ISSUE THREAD

**Issue by wlxfxy** [wenchaosong/Banner#81]
这个是在2.3.17版本下出现的情况：
![微信图片_20190928095950](https://user-images.githubusercontent.com/15390552/65809988-b6584580-e1d6-11e9-92c2-40b965863d06.jpg)
在2.3.16版本下显示则正常
![微信图片_20190928095953](https://user-images.githubusercontent.com/15390552/65809994-d38d1400-e1d6-11e9-9c7f-b64ebed6daa6.png)

**Comment by wenchaosong** [comment]
@wlxfxy  少调用了一个方法   .setOffscreenPageLimit(mList.size())
