### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by hegaojian** [wenchaosong/Banner#82]
implementation 'com.ms:Banner:2.3.17'
implementation 'com.ms:Banner-androidx:2.3.17'
集成后，什么代码都没动，直接运行项目就报错了

AS版本 3.5 
Gradle 3.5.1
开启了AndroidX

报错内容：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.ms.banner.Banner found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.Banner$1 found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.Banner$BannerPagerAdapter found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.Banner$BannerPagerAdapter$1 found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.BannerConfig found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.BannerScroller found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.BuildConfig found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.Transformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.WeakHandler found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.WeakHandler$ChainedRef found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.WeakHandler$ExecHandler found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.WeakHandler$WeakRunnable found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.holder.BannerViewHolder found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.listener.OnBannerClickListener found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.ABaseTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.AccordionTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.BackgroundToForegroundTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.CubeInTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.CubeOutTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.DefaultTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.DepthPageTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.FlipHorizontalTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.FlipVerticalTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.ForegroundToBackgroundTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.RotateDownTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.RotateUpTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.ScaleInOutTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.ScaleRightTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.ScaleTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.StackTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.TabletTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.ZoomInTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.ZoomOutSlideTransformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.transformer.ZoomOutTranformer found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.view.ArcShapeView found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  Duplicate class com.ms.banner.view.BannerViewPager found in modules classes.jar (com.ms:Banner-androidx:2.3.17) and classes.jar (com.ms:Banner:2.3.17)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

**Comment by wenchaosong** [comment]
@hegaojian 你是同时集成 2 个库吗

**Comment by hegaojian** [comment]
是的啊...

**Comment by hegaojian** [comment]
对不起，打扰了，没注意，后面那个是androidX版本，，，

**Comment by hegaojian** [comment]
作者你把那个文档改一下吧，做个说明，，，不然感觉还会有跟我一样粗心大意的人出现这种问题
