### ISSUE TITLE
指示器跳转页面

### ISSUE THREAD

**Issue by gitsmarter01** [wenchaosong/Banner#84]
无限轮播下，点击指示器能跳转指定页面吗

**Comment by wenchaosong** [comment]
@gitsmarter01  点击指示器？   指示器就那么点大小，除非你设置的很大区域，不然体验不好。不过点击跳转是可以实现的，需要自己实现

**Comment by gitsmarter01** [comment]
嗯，大屏幕上用到，加了小圆点imageview点击事件，已实现效果，谢谢@wenchaosong！
