### ISSUE TITLE
如果项目的compileSdkVersion<28的话，编译会报error: failed linking references.

### ISSUE THREAD

**Issue by HikariNoSenritsu** [wenchaosong/Banner#85]
把demo中的compileSdkVersion改成27也能复现；
兼容到28还有一定的工作量，请问有什么办法可以临时解决一下吗?

**Comment by wenchaosong** [comment]
@HikariNoSenritsu  这个其实之前是低版本的，因为有人说要跟上新版本节奏，我也认同，所以升了版本，临时解决办法只有你把我的库 copy 成 library，然后改版本
