### ISSUE TITLE
设置两端缩进属性,手动进行滑动时出现侧面没有正常缩小的问题

### ISSUE THREAD

**Issue by skyCracks** [wenchaosong/Banner#87]
设置了app:page_left_margin="20dp" 和 app:page_right_margin="20dp"
在加载网络图片的情况下，自动轮播时两端正常缩进，手动进行滑动时，滑动方向的侧面没有正常缩进，即往左滑，右侧未缩进，往右滑，左侧未缩进。

**Comment by wenchaosong** [comment]
@skyCracks  首先确定调用了 setOffscreenPageLimit

**Comment by skyCracks** [comment]
> @skyCracks 首先确定调用了 setOffscreenPageLimit

调用了 setOffscreenPageLimit ，且设置 setBannerStyle(BannerConfig.NOT_INDICATOR) 和setBannerAnimation(Transformer.Scale) ,自定义的Indicator。

**Comment by wenchaosong** [comment]
@skyCracks  我之前修改了这个方法，让使用者自己调用，引发这个问题，刚发布了新版本，改回来了，你可以试试

**Comment by skyCracks** [comment]
这个问题解决了，作者君效率很高呀，赞一个！
