### ISSUE TITLE
性能能否优化一下，当滑动的多了，有时候滑动的时候页面就是空白的

### ISSUE THREAD

**Issue by leeyushi** [wenchaosong/Banner#88]
性能能否优化一下，当滑动的多了，有时候滑动的时候页面就是空白的，但是可滑动，但是无图片显示。。。 拉着左右拖一下，才显示出来了

**Comment by leeyushi** [comment]
找不到复现原因，但是轮播的时候，有时图片就是空白的，只有按住稍微拉一点，图片就会显示出来，但是手动拖动下一张，也还是会空白，只有当前这张图结束滚动后，再把它按住，稍微拖动一点点，图片才会显示出来，由此反复多次，Banner轮播才会正常

**Comment by wenchaosong** [comment]
@leeyushi  是最新版本吗？有没有改动代码？

**Comment by leeyushi** [comment]
> @leeyushi 是最新版本吗？有没有改动代码？

版本是2.3.17，没有改动代码，用的不是BannerNew

**Comment by leeyushi** [comment]
> @leeyushi 是最新版本吗？有没有改动代码？

有头绪吗

**Comment by wenchaosong** [comment]
@leeyushi  我要看一下

**Comment by wenchaosong** [comment]
@leeyushi  这种情况我的猜测是，图片比较大，网络比较慢，加载的时间比较长，造成空白，你可以验证一下

**Comment by leeyushi** [comment]
> @leeyushi 这种情况我的猜测是，图片比较大，网络比较慢，加载的时间比较长，造成空白，你可以验证一下

不是过大造成的，因为一开始是会正常的，初始化1秒钟就加载出来了，初始化好以后也可以随意来回滑动无空白，只有运行时间久了，才有可能有几率会出现 
我把我Adapter的代码，贴出来给你看吧，看是不是跟我的代码有关系

**Comment by leeyushi** [comment]
![image](https://user-images.githubusercontent.com/23522084/68819609-746e5a80-06c3-11ea-9a85-bc350dccdd4e.png)

**Comment by leeyushi** [comment]
还有一个问题就是imageView.setScaleType，设置填充类型会无效，不知道什么原因，现在导致外边Banner布局尺寸是多大的，图片展示出来的尺寸就是多大的，如果我把Banner布局的尺寸改小一点，图片就会显示不全，设置imageView.setScaleType（所有类型都不会生效）

**Comment by wenchaosong** [comment]
@leeyushi  跟你的 glide 使用方式有关，具体的我就不指出来了

**Comment by wenchaosong** [comment]
@leeyushi  运行时间久，几率出现的问题，我暂时还没有重现，也没有头绪

**Comment by leeyushi** [comment]
imageView.setScaleType不生效的问题呢

**Comment by wenchaosong** [comment]
> imageView.setScaleType不生效的问题呢

跟你的 glide 使用方式有关，不是说了吗

**Comment by leeyushi** [comment]
> > imageView.setScaleType不生效的问题呢
> 
> 跟你的 glide 使用方式有关，不是说了吗

那你指出来正确的方式啊，我用其它框架就可以，同样的使用方式， 你又不指出来哪里不正确

**Comment by wenchaosong** [comment]
@leeyushi  我没空帮你做这些事，demo 有现成的圆角图片自定义控件，再配合 demo 的 viewholder 很简单就能实现圆角，你自己试试吧，而且我既然指出了 glide 使用问题，你可以自己尝试调试看看怎么解决，不用总想着别人帮你

**Comment by leeyushi** [comment]
> @leeyushi 我没空帮你做这些事，demo 有现成的圆角图片自定义控件，再配合 demo 的 viewholder 很简单就能实现圆角，你自己试试吧，而且我既然指出了 glide 使用问题，你可以自己尝试调试看看怎么解决，不用总想着别人帮你

问题是我在你demo库里面，用你demo里面的方法尝试只设置imageView.setScaleType，相关图片加载方式还是用你demo里的，效果是一样的，不生效

**Comment by leeyushi** [comment]
> @leeyushi 我没空帮你做这些事，demo 有现成的圆角图片自定义控件，再配合 demo 的 viewholder 很简单就能实现圆角，你自己试试吧，而且我既然指出了 glide 使用问题，你可以自己尝试调试看看怎么解决，不用总想着别人帮你

你自己尝试过，会生效吗，你把布局尺寸改小一点，原图放大一点，看填充方式会生效不

**Comment by wenchaosong** [comment]
@leeyushi  项目 demo 不管是布局调整还是 setScaleType 调整都没问题，你直接运行 demo ，然后修改看看
