### ISSUE TITLE
轮播recycleView,默认先显示的是posiion1 不是0

### ISSUE THREAD

**Issue by keaitao0321** [wenchaosong/Banner#9]
如题:
 List<List<String>> splitList = CollectionUtils.getSplitList(strings, 8);
        bannerPingpai.setBannerStyle(BannerConfig.NOT_INDICATOR);
        bannerPingpai.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {
                ToastUitl.showShort(position + "");
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });
        bannerPingpai.setPages(splitList, new HolderCreator<BannerViewHolder>() {
            @Override
            public BannerViewHolder createViewHolder() {
                return new CustomViewHolder();
            }
        }).start();

class CustomViewHolder implements BannerViewHolder<List<String>> {

        @BindView(R.id.recyclerView)
        RecyclerView mRecyclerView;

        @Override
        public View createView(Context context) {
            View view = LayoutInflater.from(context).inflate(R.layout.item_wholesale_pingpai_layout, null);
            ButterKnife.bind(this, view);
            return view;
        }

        @Override
        public void onBind(Context context, int position, List<String> data) {
            /**/ 数据绑定,这里先加载的是大list的第二个元素**
            PingPaiHotAdapter mPingPaiHotAdapter = new PingPaiHotAdapter(data);
            mRecyclerView.setLayoutManager(new GridLayoutManager(getContext(), 4));
            mRecyclerView.setAdapter(mPingPaiHotAdapter);
            mPingPaiHotAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
                @Override
                public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                    String item = mPingPaiHotAdapter.getItem(position);
                    ToastUitl.showShort(item);
                }
            });
        }
    }

**Comment by keaitao0321** [comment]
/**
     * 返回真实的位置
     *
     * @param position
     * @return 下标从0开始
     */
    private int toRealPosition(int position) {
        int realPosition = (position - 1) % count;
        if (realPosition < 0)
            realPosition += count;
        return realPosition;
    }

这个有问题吧

**Comment by wenchaosong** [comment]
@keaitao0321  Demo 里这么多 Banner 位置都是从 0 开始，你用排除法吧，你先别用你这个 RecyclerView ，用其他布局试试
