### ISSUE TITLE
右端缩进模式，当图片滑到最后一张能变成左端缩进吗？

### ISSUE THREAD

**Issue by zhangnin** [wenchaosong/Banner#91]

**Comment by zhangnin** [comment]
目前我动态去设置，会闪一下 
banner4.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int i, float v, int i1) {

            }

            @Override
            public void onPageSelected(int i) {
                Log.d("CeShiActivity", "onPageSelected：" + i);
                // 滑到最后一个，改变左右边距
                if (i == (arrList.size() - 1)) {
                    banner4.setPageMargin(getResources().getDimensionPixelSize(R.dimen.right_margin), 0);
                } else {
                    banner4.setPageMargin(0, getResources().getDimensionPixelSize(R.dimen.right_margin));
                }

            }

            @Override
            public void onPageScrollStateChanged(int i) {

            }
        });

**Comment by wenchaosong** [comment]
为什么会有这么奇葩的需求

**Comment by zhangnin** [comment]
产品看了海外的app【app名：Twitch】，在上面是有这种类型的，前面的轮播都是右边缩进，最后一张是左边缩进并且右边是填满的，我目前按上面写的这种方式改，动态设置setPadding会闪一下

**Comment by zhangnin** [comment]
您这边有什么思路去处理这种情况吗？

**Comment by wenchaosong** [comment]
你先截图看看， 最好是动图

**Comment by zhangnin** [comment]
上传不了图片、视频啊 0.0，能加个QQ吗：1281689541
