### ISSUE TITLE
两端缩进依然有问题！

### ISSUE THREAD

**Issue by PickyQiu** [wenchaosong/Banner#97]
把demo中的banner高度调大一些会出现左侧和右侧高度不同的情况！如图：
![微信图片_20200118144242](https://user-images.githubusercontent.com/35062457/72659854-ceabd480-3a00-11ea-82d9-653c1976435b.png)
修改的代码如下：
 <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="519dp"
            android:orientation="vertical">

            <com.ms.banner.Banner
                android:id="@+id/banner1"
                android:layout_width="match_parent"
                android:layout_height="519dp"
                app:page_left_margin="60dp"
                app:page_right_margin="60dp" />

            <LinearLayout
                android:id="@+id/indicator"
                android:layout_width="match_parent"
                android:layout_height="15dp"
                android:gravity="center"
                android:orientation="horizontal" />

        </LinearLayout>

**Comment by PickyQiu** [comment]
问题没描述清楚，BannerAnimation为Transformer.Scale的时候会出现这个问题！

**Comment by PickyQiu** [comment]
应该是ScaleTransformer类中这行的问题：
float scale = (position < 0) ? ((1 - SCALE_Y) * position + 1) : ((SCALE_Y - 1) * position + 1);
我自己这边改成：
float scale = (position < 0) ? ((1.1f - SCALE_Y) * position + 1) : ((SCALE_Y - 1) * position + 1);可以满足需求但是治标不治本，希望您可以解决一下！

**Comment by wenchaosong** [comment]
@PickyQiu    Transformer 这个类是框架之外的，能通过修改它实现就可以了，框架内是不需要改动的

**Comment by wenchaosong** [comment]
我目前在看有没有其他更好的

**Comment by PickyQiu** [comment]
好的  谢谢啦
